### ISSUE TITLE
ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by TheFibonacciEffect** [nngogol/PySimpleGUIDesigner#11]
Just installed it via pip in a venv and ran `PySimpleGUIDesigner` and it throws the exeption above.

**Comment by TheFibonacciEffect** [comment]
I am no expert, but maybe you need a requirenments.txt?

**Comment by nngogol** [comment]
Hello. I will add them a bit later.

**Comment by nngogol** [comment]
I added. Thanks for writing all that.
