### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [nngogol/PySimpleGUIDesigner#13]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.1.4.6. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pysimpleguidesigner -w /tmp/ext pysimpleguidesigner==0.1.4.6
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pysimpleguidesigner==0.1.4.6
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/12d/bc5a9309acccc/PySimpleGUIDesigner-0.1.4.6.tar.gz (18 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ct7k49qt/pysimpleguidesigner/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ct7k49qt/pysimpleguidesigner/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ct7k49qt/pysimpleguidesigner/pip-egg-info
         cwd: /tmp/pip-wheel-ct7k49qt/pysimpleguidesigner/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-ct7k49qt/pysimpleguidesigner/setup.py", line 17, in <module>
        with open(readmefile, "r", encoding='utf-8') as ff:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-ct7k49qt/pysimpleguidesigner/PySimpleGUIDesigner/README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by nngogol** [comment]
How can I fix this? It this a bug? Can you run me software?
Can you explain how to recreate your error, thatch? And what this error is?

**Comment by thatch** [comment]
This issue is filed by automation run by me, I'm a human, and feel free to ask
questions.  I will try to follow up with automated PRs if it's easily fixable,
but that's a bit more manual.  In most cases the fix is adding a line to your
`MANIFEST.in` that looks like `include *.md` or `include VERSION`.

The documentation for what's included is at
https://docs.python.org/3/distutils/sourcedist.html#specifying-the-files-to-distribute
and the reason why `pip install --no-binary <your project>` matters is that some
companies choose to build from source (even for pure-python projects).

A simple repro if you use setuptools is

```sh
D=$(mktemp -d)
python3 -m venv $D
python3 setup.py sdist -d $D
$D/bin/pip install $D/*.tar.gz
```

**Comment by thatch** [comment]
That said, I don't see a setup.py checked in?

**Comment by nngogol** [comment]
Hello.
Ok, I managed to re**created** this error with your shell code, thatch.
All fixed (pip version AND source code in this repo).
Try now and write me back.
*Note*: I didn't get short words at first (like `repro`), but everything is good now.

Also, can you tell about this "building from source" thing. I see you opened a lot of issues in repos. Is it automatically or you are using this packages?
Did you used my package?

**Comment by thatch** [comment]
Your latest release pysimpleguidesigner==0.1.4.7 succeeds when I run the script that initially found this issue.  Sorry, I don't use your project, I'm just trying to improve the ecosystem for everyone and your project appears in active development.
