### ISSUE TITLE
Can not run Python 3.7.2

### ISSUE THREAD

**Issue by ccanik** [nngogol/PySimpleGUIDesigner#15]
I installed with pip and trying to run from cmd in Win7. I get same error all the time. Tried uninstall and install again, didnt worked. Tried to install from source code and run, but still same error. 
I didnt find to solution.Can you help?

Python version: 3.7.2
`C:\Users\MYNAME>PySimpleGUIDesigner
PySide2/__init__.py: Unable to import shiboken2 from C:\Users\MYNAME\AppData\
Local\Programs\Python\Python37\Scripts\PySimpleGUIDesigner.exe, C:\Users\{usrNam
e}\AppData\Local\Programs\Python\Python37-32\Lib", c:\users\MYNAME\appdata\lo
cal\programs\python\python37\python37.zip, c:\users\MYNAME\appdata\local\prog
rams\python\python37\DLLs, c:\users\MYNAME\appdata\local\programs\python\pyth
on37\lib, c:\users\MYNAME\appdata\local\programs\python\python37, c:\users\ce
lil can\appdata\local\programs\python\python37\lib\site-packages
Traceback (most recent call last):
  File "c:\users\MYNAME\appdata\local\programs\python\python37\lib\runpy.py",
 line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\MYNAME\appdata\local\programs\python\python37\lib\runpy.py",
 line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\MYNAME\AppData\Local\Programs\Python\Python37\Scripts\PySimp
leGUIDesigner.exe\__main__.py", line 5, in <module>
  File "c:\users\MYNAME\appdata\local\programs\python\python37\lib\site-packa
ges\PySimpleGUIDesigner\main.py", line 5, in <module>
    from .transpiler2 import *
  File "c:\users\MYNAME\appdata\local\programs\python\python37\lib\site-packa
ges\PySimpleGUIDesigner\transpiler2.py", line 1, in <module>
    from PySide2 import QtCore, QtGui, QtWidgets
  File "c:\users\MYNAME\appdata\local\programs\python\python37\lib\site-packa
ges\PySide2\__init__.py", line 88, in <module>
    _setupQtDirectories()
  File "c:\users\MYNAME\appdata\local\programs\python\python37\lib\site-packa
ges\PySide2\__init__.py", line 54, in _setupQtDirectories
    import shiboken2
  File "c:\users\MYNAME\appdata\local\programs\python\python37\lib\site-packa
ges\shiboken2\__init__.py", line 27, in <module>
    from .shiboken2 import *
ImportError: DLL load failed: Belirtilen modül bulunamadı.
`

**Comment by nngogol** [comment]
It's `a new python version` problem. I use python 3.6 - it works without any pain.
My recommendation: **switch to python 3.6**!
Also, read this:
https://stackoverflow.com/questions/56757044/pyside2-dll-load-failed-the-specified-procedure-could-not-be-found

I don't know why do you need 3.7+ python.

**Comment by ccanik** [comment]
Switching to python 3.6 didnt worked for me. I think its all about shiboken2 and python version compability. I installed python 3.8, the most updated version, (like answer to link you send) then it worked!

Not sure, but installing older versions of PySide2 and shiboken2 could also work(not tested now, I will try).

**Comment by nngogol** [comment]
Okay. Thanks for answer.
