### ISSUE TITLE
from Designer to App Builder

### ISSUE THREAD

**Issue by gilbh** [nngogol/PySimpleGUIDesigner#16]
Hi @nngogol!

Love your nose!

I wanted to get your attention on an enhancement request I've put in for PySimpleGUI:  PySimpleGUI/PySimpleGUI#3398

Mike thought you and I should discuss. I am available on any channel.

best!
Gil

**Comment by nngogol** [comment]
xml > psg code -- done.
psg code > xml -- is not so productive, but is possible.
psg in console -- nope.
