### ISSUE TITLE
Problem with Untitled.ui example 

### ISSUE THREAD

**Issue by ChristopheMarques** [nngogol/PySimpleGUIDesigner#3]
Hi! First of all thanks for your tool, is very useful for my test application at work (we have different tests on agriculture motor) and to understand better how PySimpleGui works. 

I installed the version from pip PySimpleGUIDesigner 0.0.4.
Then I download the sources and try with ui file "C:\PySimpleGUIDesigner-master\examples_of_ui\untitled.ui"
If I open "untiled.ui" with Qt Creator (4.7.1) I see the "els" GroupBox with a series of element, but when I make "Compile" in PySimpleGUIDesigner, "error, no obj_name="els"" found" is notified.
Have you got some tips/workaround? Thanks in advance.

![immagine](https://user-images.githubusercontent.com/55753613/65601358-3d70a800-dfa2-11e9-956f-cc854d818a28.png)

**Comment by nngogol** [comment]
fixed. Try `pip install PuSimpleGUIDesigner --no-cache` and run Designer with `PySimpleGUIDesigner`
