### ISSUE TITLE
CLI wrong parameters in readme.md

### ISSUE THREAD

**Issue by ChristopheMarques** [nngogol/PySimpleGUIDesigner#4]
In readme.md files xmlfile and objname parameters are written with "--" and not with "-".

**Run GUI:**
PySimpleGUIDesigner
**Use options:**
PySimpleGUIDesigner **--xmlfile**="~/folder1/test.ui" **--objname**="somegroupBox"

![immagine](https://user-images.githubusercontent.com/55753613/65602579-67c36500-dfa4-11e9-860c-cb3778909b63.png)

**Comment by nngogol** [comment]
Hi! Yes, I know, that this tool is broken.
I'm working on this.
For now - try to write python nested lists by hand.

**Comment by nngogol** [comment]
Thanks for the issue, all fixed.
