### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'metadata'

### ISSUE THREAD

**Issue by valeriy67** [nngogol/PySimpleGUIDesigner#5]
Hello!
After installation and trying to start PySimpleGUIDesigner I get an error:
TypeError: __init__() got an unexpected keyword argument 'metadata'

**Comment by nngogol** [comment]
Привет, Валерий.
У тебя старая версия PySimpleGUI. Обнови ее вот этой командой:
```bash
pip install PySimpleGUI -U --no-cache
```
Это не проблема PySimpleGUIDesigner.
Если не поможет - дашь мне еще информацию про проблему.

---

English version:
You have an old version of PySimpleGUI. Update with `pip install PySimpleGUI -U --no-cache`

**Comment by valeriy67** [comment]
Привет!
Вот ответ на команду  pip install PySimpleGUI -U --no-cache

Requirement already up-to-date: PySimpleGUI in ./venv/lib/python3.6/site-packages

**Comment by nngogol** [comment]
Ух, у тебя еще и виртуальное окружение. Глобально обнови питон.

Сама ошибка `TypeError: init() got an unexpected keyword argument 'metadata'` - это говорит, что используется одна из старых версий PSG. В свежей версии у всех элементов есть параметр metadata (который я предложил и он теперь в библиотеке везде), который можно юзать для хранения всяких данных, которые нужно чисто лично тебе.

Если проблемы со сих пор есть - пиши.

**Comment by valeriy67** [comment]
Спасибо!
