### ISSUE TITLE
not work with PyQt5

### ISSUE THREAD

**Issue by milen-prg** [nngogol/PySimpleGUIDesigner#6]
I try to use PySimpleGUIDesigner with PyQt5 (no PySide 2), but the DLL can't be imported, because the program search for PySide.

Is it possible to use PySimpleGUIDesigner with Python + PyQt5?

**Comment by nngogol** [comment]
Well, try to replace all `PySide2` to `PyQt5` in all source code files, that is connected.

**Comment by nngogol** [comment]
Is it working?
